config/routes.rb
ForgotNotIi::Application.routes.draw do
  resources :funerals

  devise_for :guests, :controllers => { :registrations => "registrations" }
  resources :guests do
    member do
      get 'myaccount'
    end
  end

  devise_for :keyholders, :controllers => { :registrations => "registrations" }
  resources :keyholders do
    member do
      get 'myaccount'
    end
  end

  devise_for :users
  resources :users do
    member do
      get 'myaccount'
    end
  end
  

  get "public/index"
  
  root :to => "public#index"

  

end

app/models/keyholder.rb
class Keyholder < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
         
  belongs_to :user
  
end

app/controllers/keyholders_controller.rb
class KeyholdersController < ApplicationController
  before_action :set_keyholder, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:myaccount]
  before_filter :authorize_keyholder, only: [:myaccount]

  # GET /keyholders
  # GET /keyholders.json
  def index
    @keyholders = Keyholder.all
  end

  # GET /keyholders/1
  # GET /keyholders/1.json
  def show
  end

  # GET /keyholders/new
  def new
    @keyholder = Keyholder.new
  end

  # GET /keyholders/1/edit
  def edit
  end

  # POST /keyholders
  # POST /keyholders.json
  def create
    @keyholder = Keyholder.new(keyholder_params)
    @user = current_user

    respond_to do |format|
      if @keyholder.save
        format.html { redirect_to @keyholder, notice: 'Keyholder was successfully created.' }
        format.json { render action: 'show', status: :created, location: @keyholder }
      else
        format.html { render action: 'new' }
        format.json { render json: @keyholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keyholders/1
  # PATCH/PUT /keyholders/1.json
  def update
    respond_to do |format|
      if @keyholder.update(keyholder_params)
        format.html { redirect_to @keyholder, notice: 'Keyholder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @keyholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keyholders/1
  # DELETE /keyholders/1.json
  def destroy
    @user = @keyholder.user
    @keyholder.destroy
    @user.keyholder_id = nil
    @user.save
    respond_to do |format|
      format.html { redirect_to keyholders_url }
      format.json { head :no_content }
    end
  end
  
  def myaccount
    if user_signed_in?
      redirect_to :controller => "/users", :id => current_user.id, :action => 'myaccount'
    elsif keyholder_signed_in?
    @keyholder = Keyholder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
    else
      redirect_to root_path, notice: 'Please login to view your account'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyholder
      @keyholder = Keyholder.find(params[:id])
    end
    
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def keyholder_params
      params.require(:keyholder).permit(:username, :first_name, :last_name, :user_id, :house, :postcode, :keyholder)
    end
    
end

app/helpers/keyholders_helper.rb
module KeyholdersHelper
end

app/views/keyholders/_form.html.erb
<%= form_for(@keyholder) do |f| %>
  <% if @keyholder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyholder.errors.count, "error") %> prohibited this keyholder from being saved:</h2>

      <ul>
      <% @keyholder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><%= f.label :username %><br />
  <%= f.text_field :username, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :house %><br>
    <%= f.text_field :house %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keyholders/edit.html.erb
<h1>Editing keyholder</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyholder %> |
<%= link_to 'Back', keyholders_path %>

app/views/keyholders/index.html.erb
<h1>Listing keyholders</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>First name</th>
      <th>Last name</th>
      <th>User</th>
      <th>House</th>
      <th>Postcode</th>
      <th>Keyholder for</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @keyholders.each do |keyholder| %>
      <tr>
        <td><%= keyholder.username %></td>
        <td><%= keyholder.first_name %></td>
        <td><%= keyholder.last_name %></td>
        <td><%= keyholder.user_id %></td>
        <td><%= keyholder.house %></td>
        <td><%= keyholder.postcode %></td>
        <td><% if keyholder.user %>
        	<%= keyholder.user.first_name %> <%= keyholder.user.last_name %>
        	<% else %>
        	<p>n/a</p></td>
        	<% end %>
        <td><% if current_user || current_keyholder || current_guest %>
        		<% if can? :read, keyholder %>
		        	<%= link_to 'Show', keyholder %>
		        	<% else %>
		        	<p>n/a</p>
		        	<% end %></td>
		        <td><% if can? :update, keyholder %>
		        	<%= link_to 'Edit', edit_keyholder_path(keyholder) %>
		        	<% else %>
		        	<p>n/a</p>
		        	<% end %></td>
		        <td><% if can? :destroy, keyholder %>
		        	<%= link_to 'Destroy', keyholder, method: :delete, data: { confirm: 'Are you sure?' } %>
		        	<% else %>
		        	<p>n/a</p>
		        	<% end %></td>
		     <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Keyholder", new_keyholder_registration_path %>

app/views/keyholders/myaccount.html.erb
<p id="notice"><%= notice %></p>
<h1>My Keyholder Account</h1>
<p>
  <strong>Username:</strong>
  <%= @keyholder.username %>
</p>

<p>
  <strong>First name:</strong>
  <%= @keyholder.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @keyholder.last_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @keyholder.user_id %>
</p>

<p>
  <strong>House:</strong>
  <%= @keyholder.house %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @keyholder.postcode %>
</p>

<%= link_to 'Edit', edit_keyholder_path(@keyholder) %> |
<%= link_to 'Back', keyholders_path %>

app/views/keyholders/new.html.erb
<h1>New keyholder</h1>

<%= render 'form' %>

<%= link_to 'Back', keyholders_path %>

app/views/keyholders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @keyholder.username %>
</p>

<p>
  <strong>First name:</strong>
  <%= @keyholder.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @keyholder.last_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @keyholder.user_id %>
</p>

<p>
  <strong>House:</strong>
  <%= @keyholder.house %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @keyholder.postcode %>
</p>

<%= link_to 'Edit', edit_keyholder_path(@keyholder) %> |
<%= link_to 'Back', keyholders_path %>