config/routes.rb
ForgotNotIi::Application.routes.draw do
  resources :funerals

  devise_for :guests, :controllers => { :registrations => "registrations" }
  resources :guests do
    member do
      get 'myaccount'
    end
  end

  devise_for :keyholders, :controllers => { :registrations => "registrations" }
  resources :keyholders do
    member do
      get 'myaccount'
    end
  end

  devise_for :users
  resources :users do
    member do
      get 'myaccount'
    end
  end
  

  get "public/index"
  
  root :to => "public#index"

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
         
  has_one :keyholder, dependent: :destroy
  has_one :guest, dependent: :destroy
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:myaccount]
  before_filter :authorize, only: [:myaccount]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
     @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  def myaccount
    if user_signed_in?
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
    else
      redirect_to root_path, notice: 'Please login to view your account'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :middle_names, :last_name, :date_of_birth, :gender, :line_1, :line_2, :line_3, :town, :county, :postcode, :contact_number,
                                   :username, :keyholder_id, :guest_id, :user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_names %><br>
    <%= f.text_field :middle_names %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.text_field :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :line_1 %><br>
    <%= f.text_field :line_1 %>
  </div>
  <div class="field">
    <%= f.label :line_2 %><br>
    <%= f.text_field :line_2 %>
  </div>
  <div class="field">
    <%= f.label :line_3 %><br>
    <%= f.text_field :line_3 %>
  </div>
  <div class="field">
    <%= f.label :town %><br>
    <%= f.text_field :town %>
  </div>
  <div class="field">
    <%= f.label :county %><br>
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br>
    <%= f.text_field :contact_number %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :keyholder_id %><br>
    <%= f.number_field :keyholder_id %>
  </div>
  <div class="field">
    <%= f.label :guest_id %><br>
    <%= f.number_field :guest_id %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Middle names</th>
      <th>Last name</th>
      <th>Date of birth</th>
      <th>Gender</th>
      <th>Line 1</th>
      <th>Line 2</th>
      <th>Line 3</th>
      <th>Town</th>
      <th>County</th>
      <th>Postcode</th>
      <th>Contact number</th>
      <th>Username</th>
      <th>Keyholder</th>
      <th>Guest</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.middle_names %></td>
        <td><%= user.last_name %></td>
        <td><%= user.date_of_birth %></td>
        <td><%= user.gender %></td>
        <td><%= user.line_1 %></td>
        <td><%= user.line_2 %></td>
        <td><%= user.line_3 %></td>
        <td><%= user.town %></td>
        <td><%= user.county %></td>
        <td><%= user.postcode %></td>
        <td><%= user.contact_number %></td>
        <td><%= user.username %></td>
        <td><%= user.keyholder_id %></td>
        <td><%= user.guest_id %></td>
        <td><% if current_user || current_keyholder || current_guest %>
        		<% if can? :read, user %>
		        	<%= link_to 'Show', user %>
		        	<% else %>
		        	<p>n/a</p>
		        	<% end %></td>
		        <td><% if can? :update, user %>
		        	<%= link_to 'Edit', edit_user_path(user) %>
		        	<% else %>
		        	<p>n/a</p>
		        	<% end %></td>
		        <td><% if can? :destroy, user %>
		        	<%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
		        	<% else %>
		        	<p>n/a</p>
		        	<% end %></td>
		   <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/myaccount.html.erb
<p id="notice"><%= notice %></p>
<h1>My Account</h1>
<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Middle names:</strong>
  <%= @user.middle_names %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @user.date_of_birth %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Line 1:</strong>
  <%= @user.line_1 %>
</p>

<p>
  <strong>Line 2:</strong>
  <%= @user.line_2 %>
</p>

<p>
  <strong>Line 3:</strong>
  <%= @user.line_3 %>
</p>

<p>
  <strong>Town:</strong>
  <%= @user.town %>
</p>

<p>
  <strong>County:</strong>
  <%= @user.county %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @user.postcode %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @user.contact_number %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Keyholder:</strong>
  <%= @user.keyholder.first_name %> <%= @user.keyholder.last_name %>
</p>

<p>
  <strong>Guest account set up?:</strong>
  <% if @user.guest.present? %>Yes
  <% else %>No
  <% end %>
</p>


<%= link_to 'Funeral Plans', 
  			current_user.funeral.present? ? 
    		funeral_path(current_user.funeral) : 
    		new_funeral_path %><br />
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Middle names:</strong>
  <%= @user.middle_names %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @user.date_of_birth %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Line 1:</strong>
  <%= @user.line_1 %>
</p>

<p>
  <strong>Line 2:</strong>
  <%= @user.line_2 %>
</p>

<p>
  <strong>Line 3:</strong>
  <%= @user.line_3 %>
</p>

<p>
  <strong>Town:</strong>
  <%= @user.town %>
</p>

<p>
  <strong>County:</strong>
  <%= @user.county %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @user.postcode %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @user.contact_number %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Keyholder:</strong>
  <%= @user.keyholder_id %>
</p>

<p>
  <strong>Guest:</strong>
  <%= @user.guest_id %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>