config/routes.rb
ForgotNotIi::Application.routes.draw do
  resources :funerals

  devise_for :guests, :controllers => { :registrations => "registrations" }
  resources :guests do
    member do
      get 'myaccount'
    end
  end

  devise_for :keyholders, :controllers => { :registrations => "registrations" }
  resources :keyholders do
    member do
      get 'myaccount'
    end
  end

  devise_for :users
  resources :users do
    member do
      get 'myaccount'
    end
  end
  

  get "public/index"
  
  root :to => "public#index"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForgotNotIi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="user_nav">
	  <% if user_signed_in? %>
	    Signed in as <%= current_user.username %>. Not you?
	    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	  <% else %>
	    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %> as a User.
	  <% end %>
	</div>
	<div id="keyholder_nav">
	  <% if keyholder_signed_in? %>
	    Signed in as <%= current_keyholder.username %>. Not you?
	    <%= link_to "Sign out", destroy_keyholder_session_path, :method => :delete %>
	  <% else %>
	    <%= link_to "Sign up", new_keyholder_registration_path %> or <%= link_to "sign in", new_keyholder_session_path %> as a Keyholder.
	  <% end %>
	</div>
	<div id="guest_nav">
	  <% if guest_signed_in? %>
	    Signed in as <%= current_guest.username %>. Not you?
	    <%= link_to "Sign out", destroy_guest_session_path, :method => :delete %>
	  <% else %>
	    <%= link_to "Sign up", new_guest_registration_path %> or <%= link_to "sign in", new_guest_session_path %> as a Guest.
	  <% end %>
	</div>
	<p class="notice"><%= notice %></p><p class="error"><%= flash[:error] %></p>

<%= yield %>

</body>
</html>